# fly.toml app configuration file generated for ssjcrm on 2026-01-07T15:17:05-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssjcrm'
primary_region = 'sjc'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = 'bin/rails db:prepare'

[env]
  ACTIVE_STORAGE_SERVICE = 'tigris'
  RAILS_LOG_TO_STDOUT = '1'
  RAILS_SERVE_STATIC_FILES = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
